---
apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: golden-image
type: Opaque
stringData:
  token: REPLACE_WITH_YOUR_GITHUB_TOKEN
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-password
  namespace: golden-image
type: Opaque
stringData:
  password: REPLACE_WITH_REDIS_PASSWORD
